#!/bin/bash

# backup-create
# create a backup image file
# by robert klebe, dotpointer

# changelog
# 2015-06-06 12:45:13
# 2016-12-27 19:13:29
# 2017-03-07 08:56:02
# 2018-06-28 12:28:00 - adding confirmation
# 2018-06-28 15:43:00 - description edit

# make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

echo "This will create an image file for backup storage named imagefile.img in the current directory.";

read -p "Type y to continue, or anything else to quit: " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
	exit 1;
fi

echo "Creating image file imagefile.img...";
# create a x GB image file - do this locally
dd if=/dev/urandom of=imagefile.img bs=1M count=20480

echo "Creating loop device...";
# make loop device - do this locally
losetup /dev/loop0 imagefile.img

echo "Wiping header of loop device...";
# if we don't do this we get
# "Cannot wipe header on device /dev/loop0."
dd if=/dev/zero count=2048 of=/dev/loop0

echo "Inializing LUKS format on the loop device...";
# initialize img file - do this locally - NOTE, write YES in uppercase
cryptsetup luksFormat /dev/loop0

echo "Opening LUKS device..."
# create a device in /dev/mapper/name - do this locally
cryptsetup luksOpen /dev/loop0 backuploop

echo "Formatting LUKS device...";
# format the device - do this locally
mkfs.ext4 /dev/mapper/backuploop

echo "Done";
