#!/bin/bash
# changelog
# 2021-01-29 21:41:03
# 2022-06-10 18:10:00
WNDTITLE=$(xwininfo -tree -root | grep 'Messenger'|head -n1);
# match: "   0x0-9/a-z "(Messenger)": anything"
WNDTITLE=$(echo $WNDTITLE|sed 's/\s*0x[0-9a-z]*\s*"\(Messenger\)": .*/\1/');
if [ "$WNDTITLE" != "Messenger" ] && [ "$WNDTITLE" != "caprine" ]; then
  echo "$WNDTITLE";
  return;
fi
echo " ";
