#!/usr/bin/php
<?php

	# rename file using EXIF data artist and title
	# by robert klebe, dotpointer
	# changelog
	# 2017-03-25 16:39:37 - initial version
	# 2017-03-25 16:58:00 - minor fixes

	# defaults
	$exiftool = '/usr/bin/exiftool';
	$input = false;
	$confirmed = false;

	# get options
	$opts = getopt('hi:y', array('help', 'input:', 'yes'));

	# check options
	foreach ($opts as $k => $v) {
		switch ($k) {
			case 'y':
			case 'yes':
				$confirmed = true;
				break;
			case 'i': # input file
			case 'input':
				$input = $v;
				break;
			case 'h': # help
			case 'help':
?>
Read EXIF data of (MP3) file and rename using artist and title in data.

Usage: <?php echo basename(__FILE__); ?> <options>

Options:
-i <filename>, --input <filename>
	Input file to rename
-y, --yes
	Answer yes to confirm question.
-h, --help
<?php
				die(1);
		}
	}

	# make sure exiftool exists
	if (!file_exists($exiftool)) {
		echo 'Exiftool is missing: '.$exiftool."\n";
		die(1);
	}

	# make sure input file is specified
	if (!$input) {
		echo 'No input file specified.'."\n";
		die(1);
	}

	# make sure file exists
	if (!file_exists($input)) {
		echo 'File not found: '.$input."\n";
		die(1);
	}

	# get full input name
	$input = realpath($input);

	# make sure file exists after real path
	if (!file_exists($input)) {
		echo 'File not found: '.$input."\n";
		die(1);
	}

	# read exif data
	unset($c, $o, $r);
	$c = $exiftool.' -j '.escapeshellarg($input);
	exec($c, $o, $r);
	if ($r !== 0) {
		echo 'Failed running '.$c."\n";
		die(1);
	}

	# decode json data
	$exifdata = json_decode(implode("\n", $o), true);
	if (!$exifdata || !isset($exifdata[0])) {
		echo 'Failed decoding JSON data from '.$exiftool."\n";
		die(1);
	}
	$exifdata = $exifdata[0];

	# make sure artist and title is there
	if (!isset($exifdata['Artist'], $exifdata['Title'])) {
		echo 'Exifdata is missing artist or title.'."\n";
		die(1);
	}

	# cleanup artist and title
	foreach (array('Artist', 'Title') as $key) {
		$exifdata[$key] = trim(str_replace(
			array(
				'/',
				'\\'
			),
			array(
				'-',
				'-'
			),
			$exifdata[$key]
		));
	}

	# make sure artist and title is long enough
	if (!strlen($exifdata['Artist']) || !strlen($exifdata['Title'])) {
		echo 'Artist or title is empty in exifdata.'."\n";
		die(1);
	}

	# extract path, name and extension
	$currentname = basename($input);
	$extension = strrpos($currentname, '.') !== false ? substr($currentname, strrpos($currentname, '.') + 1) : '';
	$currentname = strrpos($currentname, '.') !== false ? substr($currentname, 0, strrpos($currentname, '.')) : $currentname;
	$newname = $exifdata['Artist'].' - '.$exifdata['Title'];
	$path = substr($input, 0, strrpos($input, '/') + 1);
	$output = $path.$newname.(strlen($extension) ? '.'.$extension : '');

	# check if new name already is the same as old name
	if ($newname === $currentname) {
		echo 'Already matching tag name: '.$input."\n";
		die(0);
	}

	# make sure output file does not exist
	if (file_exists($output)) {
		echo 'Output file exists: '.$output."\n";
		die(1);
	}

	# echo 'Current name: >'.$currentname.'<'."\n";
	# echo 'Extension   : >'.$extension.'<'."\n";
	# echo 'Tag name    : >'.$newname.'<'."\n";
	# echo 'Directory   : >'.$path.'<'."\n";
	echo 'Input       : "'.$input.'"'."\n";
	echo 'Output      : "'.$output.'"'."\n";

	# ask user if not bypassed
	if (!$confirmed) {
		$question = 'Do you want to continue';
		$line = strtolower(trim(readline($question.'? [Y/n]')));
		if(!$line || $line !== 'y') {
			echo 'Aborting'."\n";
			die(0);
		}
	}

	# make sure output file does not exist
	if (file_exists($output)) {
		echo 'Output file exists: '.$output."\n";
		die(1);
	}

	# rename file
	echo 'Renaming "'.$input.'" -> "'.$output.'"'."\n";
	if (!rename($input, $output)) {
		echo 'Failed renaming file: "'.$input.'" -> "'.$output.'"'."\n";
		die(1);
	}

	die(0);
?>
