#!/usr/bin/php
<?php

# changelog
# 2020-11-11 17:34:39
# 2023-03-03 19:00:00

$wholename = isset($argv[1]) ? $argv[1] : '';

if (!strlen($wholename)) {
  die(1);
}

$basename = $wholename;
# name is something-n...
if (preg_match('/^.*\-\d+$/', $basename)) {
  # remove all after the dash
  $basename = substr($basename, 0, strrpos($basename, '-') + 1);
# name does not end with a dash
} else if (substr($basename, -1) !== '-') {
  # append a dash
  $basename = $basename.'-';
}

$nameslashes = substr_count($basename, '/');

exec('git branch -va', $o, $r);
if ($r !== 0) {
  die(1);
}

$on = array();
foreach ($o as $k => $line) {
  $line = trim($line);
  if (!strlen($line)) {
    continue;
  }
  $line = substr($line, 0, strpos($line, ' '));
  while (substr_count($line, '/') > $nameslashes) {
    $line = substr($line, strpos($line, '/') + 1);
  }
  $on[] = $line;
}
$o = $on;

$i = 0;
$tryname = '';
do {
  $i++;
  $tryname = $basename.$i;
} while (in_array($tryname, $o));

echo $tryname;

?>
