#!/bin/bash

# changelog
# 2017-03-15 15:14:00 - first version
# 2018-07-31 14:43:00 - adding root check
# 2018-08-11 10:21:00 - adding remote name check
# 2018-10-16 13:17:00 - adding name keyword check
# 2019-02-25 11:32:00 - adding allowance to create branch even if it exists
# 2020-04-23 16:23:50
# 2020-11-11 17:12:00 - adding better name finder
# 2022-02-15 13:10:00 - no gh and rm prefixes
# 2023-01-09 12:13:00 - adding base branch argument
# 2023-10-28 22:50:00 - using gitbranchfindbetternamebash instead of gitbranchfindbetternamephp
# 2023-10-29 01:02:00 - using gitbranchfindbetternamephp first since bash version is slow
ME=$(whoami);

if [[ $ME == "root" ]]; then
  echo "Cannot make branches as root.";
  exit 1;
fi

NAME=$1;
# make sure gh (GitHub) or rm (Redmine) is in the name, otherwise warn
#if [[ ! $NAME == *"gh"* ]] && [[ ! $NAME == *"rm"* ]]; then
#  read -p "Missing keywords gh and rm in branch name. Do you really want to continue? [y/n] " -n 1 -r;
#  echo;
#  if [[ ! $REPLY =~ ^[Yy]$ ]]
#  then
#    echo "Stopping, not creating the branch.";
#    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
#  fi
#fi

BASEBRANCH=$2;

# if the better name finder is available then run it
GITBRANCHFINDBETTERNAME="";
if [[ -x "$(command -v php)" && -x "$(command -v gitbranchfindbetternamephp)" ]]; then
  GITBRANCHFINDBETTERNAME="gitbranchfindbetternamephp"
elif [[ -x "$(command -v gitbranchfindbetternamebash)" ]]; then
  GITBRANCHFINDBETTERNAME="gitbranchfindbetternamebash";
fi

if [[ ! -z $GITBRANCHFINDBETTERNAME ]]; then
  BETTERNAME=$($GITBRANCHFINDBETTERNAME "$NAME");
  if [[ -n "$BETTERNAME" ]] && [[ "$NAME" != "$BETTERNAME" ]]; then
    read -p "Will use $BETTERNAME instead, press [n] to use $NAME anyway: " -n 1 -r;
      echo;
      if [[ ! $REPLY =~ ^[Nn]$ ]]
      then
        NAME="$BETTERNAME";
      fi
  fi
fi

# problem: this does only check local remote status, a pull is requested
git branch -v -a|grep "$NAME";

if [ $? -ne 1 ]; then
  echo 'Found already existing branches with that name or similar by running git branch -v -a.';
  read -p "Do you really want to use $NAME anyway? [y/n] " -n 1 -r;
    echo;
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
      echo "Stopping, not creating the branch.";
        [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
    fi
fi

# switch to master
git checkout master
if [[ $? -ne 0 ]]; then
  echo "Failed to checkout master";
  exit $?;
fi

if [[ ! -z $BASEBRANCH ]]; then
  LOCALBRANCHES=$(git branch|grep -E "^[*| ] ${BASEBRANCH}.*$");
  if [[ -z $LOCALBRANCHES ]]; then
    read -p "The base branch does not exist locally, do you want to try to pull it? [y/n] " -n 1 -r;
    echo;
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1;
    fi
    git branch $BASEBRANCH remotes/origin/$BASEBRANCH;
    if [[ $? -ne 0 ]]; then
      echo "Failed to switch to basebranch";
      exit 1;
    fi
    git checkout $BASEBRANCH;
    if [[ $? -ne 0 ]]; then
      echo "Failed checking out base branch";
      exit 1;
    fi
    git pull;
    if [[ $? -ne 0 ]]; then
      echo "Failed pulling base branch";
      exit 1;
    fi
  fi
fi

# switch to master
git checkout master
if [[ $? -ne 0 ]]; then
  echo "Failed to checkout master";
  exit $?;
fi

if [[ ! -z $BASEBRANCH ]]; then
  git checkout -b $NAME $BASEBRANCH
else
  # checkout a new branch locally
  git checkout -b $NAME
fi

if [[ $? -ne 0 ]]; then
  echo "Failed to checkout new branch";
  exit $?;
fi

# push the new branch remote, if the branch already exists then it will refuse without force
git push origin $NAME:$NAME
if [[ $? -ne 0 ]]; then
  echo "Failed to push origin";
  exit $?;
fi

# set it to track the branch upstream
git push --set-upstream origin $NAME
if [[ $? -ne 0 ]]; then
  echo "Failed to push set upstream origin";
  exit $?;
fi

# print out what branch that is currently active
git branch
if [[ $? -ne 0 ]]; then
  echo "Faild to list local branches";
  exit $?;
fi
