#!/bin/bash

# igrepa
# recursively find files containing a case-insensitive text string
# by robert klebe, dotpointer

# changelog
# 2017-04-06 08:45:00
# 2018-06-28 17:31:00

grep -rni "$1" --color=auto ./
