#!/usr/bin/php
<?php

# phpdircheck
# php lint check a directory recursively and stop if any errors occour
# by robert klebe

# example bash file which checks php files before publishing data to a webroot:
#
# phpdircheck $SOURCE
# if [ $? -eq 0 ]; then
#	echo "Publishing data: $SOURCE -> $TARGET";
#        # sync the source with the target, */=recursive, note that we must specify folder excludes first for some reason
#	 rsync -av --exclude='subdomains' --include='*/' --include='*.map' --include='*.po' --include='*.mo' --include='*.png' --include='*.html' --include='*.ttf' --include='*.eot' --include='*.svg' --include='*.woff' --include='*.jpg' --include='*.gif' --include='*.ico' --include='*.swf' --include='*.php' --include='*.css' --include='*.js' --include='robots.txt' --exclude='*' $SOURCE $TARGET
# fi

# changelog
# 2013-11-02 14:34 - initial version
# 2014-10-22 22:39 - cleanup
# 2014-10-22 22:46:33
# 2015-09-02 18:29:02 - cleanup and bugfix
# 2016-09-21 20:38:18 - adding progressbar
# 2016-09-21 21:31:02 - updated progressbar
# 2017-02-04 23:11:00 - updated progressbar
# 2018-06-29 14:56:00 - cleanup
# 2018-06-29 15:13:56
# 2018-07-19 19:29:32 - indentation change, tab to 2 spaces
# 2022-02-23 12:07:00 - adding -a, -g, -gp, -h

function progressbar($part, $total) {

  # character length for progress bar
  $pb_length = 10;

  # calculate the part
  $pb_part = round( ($part > 0 && $total > 0) ? ($part/$total) * $pb_length : 0);
  # calculate the total
  $pb_total = $pb_length;

  return
    '['.
    str_repeat('#', ($part < $total && $pb_part > 0) ? $pb_part - 1 : $pb_part ).

    ($part < $total && $pb_part > 0 ? '>' : '').

    str_repeat('.', $pb_total - $pb_part).
    '] '.
    # the first number is the actual amount of characters in the
    # resulting string, and we want 000.000, so that's 7
    sprintf("%07.3f", ($part > 0 && $total > 0) ? ($part / $total) * 100 : 0, 1).
    '% '.
    str_pad($part, strlen($total), '0', STR_PAD_LEFT).
    '/'.
    $total.
    ' '
    ;
}

if (!isset($argv[1])) {
    echo 'Option or path must be specified'."\n";
    exit(1);
}

# git repo - all files
if ($argv[1] === '-g') {
  $c = 'git ls-tree --full-tree -r --name-only HEAD';
  exec($c, $files, $r);
  if ($r !== 0) {
    echo 'Failed: '.$c."\n";
    exit(2);
  }
  if (!count($files)) {
    echo 'No files found.'."\n";
    exit(2);
  }
# git diff - modified files
} else if ($argv[1] === '-gp') {
  $c = 'git status --porcelain';
  exec($c, $files, $r);
  if ($r !== 0) {
    echo 'Failed: '.$c."\n";
    exit(2);
  }
  if (!count($files)) {
    echo 'No files found.'."\n";
    exit(2);
  }
  foreach ($files as $k => $v) {
    $files[$k] = substr($v, 3);
  }

# help
} else if (in_array($argv[1], array('-h', '--help'))) {
?>Usage: <?php echo basename(__FILE__) ?> <directory|options>

Options:
-a
  Check all files in the current directory, not only .php files

-g
  Check all files in a git repository in the current directory
  (git ls-tree --full-tree -r --name-only HEAD)

-gp
  Check modified files in a git repository in the current directory
  (git diff --porcelain)

-h, --help
  Print this information
<?php
  exit(1);

# -a or path
} else {

  if ($argv[1] === '-a') {
    $path = '.';
  } else {
    $path = $argv[1];
  }
  if (!file_exists($path) || !is_dir($path)) {
    echo 'Directory does not exist: '.$path."\n";
    exit(1);
  }
  # set working dir
  chdir($path);

  # do a find on the dir
  $cmd = 'find '.escapeshellarg($path).($argv[1] === '-a' ? '' : ' -iname "*.php"');
  $files = shell_exec($cmd);
  if (!$files) {
    echo 'No files found.'."\n";
    exit(2);
  }
  # split the lines by newline
  $files = explode("\n", trim($files));
}

$total = count($files);
$l = strlen((string)$total);
echo 'PHP Lint-checking '.$total.' files'."\n";

# walk files
$prevfile = '';
foreach ($files as $nr => $file) {
  if (!file_exists($file)) {
    # echo 'File does not exist: '.$file."\n";
    continue;
  }

  unset($o, $r);
  $cmd = 'php -l '.escapeshellarg($file);
  exec($cmd, $o, $r);

  if ($r) {
    echo "\n".'Fail: '.$file."\n";
    echo (is_array($o) ? trim(implode("\n", $o)) : $o)."\n";
    exit(3);
  }
  # echo sprintf('%0'.$l.'d',  ($nr + 1)).'/'.$total.' ('.( sprintf('%03d', round(( ($nr + 1)/$total)*100) )).'%) ok, checked: '.$file."\r";

  # blank previous line
  echo progressbar($nr + 1, $total).' checked: '.str_repeat(' ', strlen($prevfile))."\r";

  # write status
  echo progressbar($nr + 1, $total).' checked: '.$file."\r";
  $prevfile = $file;
}

# blank previous line
echo progressbar($nr + 1, $total).' checked: '.str_repeat(' ', strlen($prevfile))."\r";

# write status
echo progressbar($nr + 1, $total).' check completed'."\r\n";

exit(0);
?>
