#!/usr/bin/php
<?php

		# to walk a directory for text files and then output all contents of them with path and last modified-date, so it can be stored in one file, may also delete original file if requested
		# bug: lines below file path gets too long if there are swedish characters in the name

		date_default_timezone_set('Europe/Stockholm');

		$delete = isset($argv[1]) && $argv[1] === '-d' ? true : false;

		# 2014-09-11 08:55:20 - base version
		# 2014-10-25 21:10:00 - update		

		$rootpath = './';
		# get a list of files
		$c = 'find '.escapeshellarg($rootpath).' -type f -iname "*.txt"';
		exec($c, $o, $r);
    		if ($r !== 0) die('Could not do find.');
    	
   		
		$files = $o;
		
		foreach ($files as $file) {
		
			# get contents
			$contents = file_get_contents($file);
		
			# make sure we get all
			if ($contents === false) die('Failed reading: '.$file);
				
			$contents = utf8_encode($contents);
				
			# make header
			$header = trim(implode(" / ", explode("/", substr($file, 2))   ).' - '.date('Y-m-d H:i:s', filemtime($file)));
			
			# print header
			echo $header."\n";
			
			# print line below header
			echo str_repeat('-', strlen($header))."\n\n";
			
			# get and print file contents
			echo trim($contents)."\n\n";
			
		    	# shall file be deleted?
			if ($delete) {			    
			    	unlink($file);
			}
		}
?>
