#!/bin/bash

# vmcdide
# virtualbox, set machine optical ide device disc
# by robert klebe, dotpointer

# changelog
# 2018-06-29 16:17:00
# 2014-10-01 12:08:16
# 2018-06-29 16:18:00 - cleanup

NAME=$1
MEDIUM=$2
if [ -z "$NAME" ]; then
	echo "Name of VM must be given, path to disk can be given.";
	exit 1
fi

if [ -z "$MEDIUM" ]; then
	MEDIUM='emptydrive'
fi

# list and scan for VM:s
VMS=$(VBoxManage list vms)
if [[ ! $VMS == *"$1"* ]]; then
	echo "VM $1 not found.";
fi

VBoxManage storageattach "$NAME" --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium $MEDIUM
