#!/bin/bash

# vmfloppy
# virtualbox, insert and eject machine floppy disks
# by robert klebe, dotpointer

# changelog
# 2014-10-01 12:09:34
# 2018-06-29 16:34:00
# 2018-07-19 19:29:34 - indentation change, tab to 2 spaces

NAME=$1
MEDIUM=$2
if [ -z "$NAME" ]; then
  echo "Name of VM must be given, path to disk can be given.";
  exit 1
fi

if [ -z "$MEDIUM" ]; then
  MEDIUM='emptydrive'
fi

# list and scan for VM:s
VMS=$(VBoxManage list vms)
if [[ ! $VMS == *"$1"* ]]; then
  echo "VM $1 not found.";
fi

VBoxManage storageattach "$NAME" --storagectl "FDD Controller" --port 0 --device 0 --type fdd --medium $MEDIUM
