#!/bin/bash

# vmoff
# virtualbox, turn a machine off
# by robert klebe, dotpointer

# changelog
# 2014-10-01 12:09:29
# 2018-06-29 17:00:00 - cleanup

# if machine is specified, stop that
if [ -n "$1" ]; then
	VBoxManage controlvm "$1" acpipowerbutton
# otherwise stop them all
else
	echo "Machine name must be specified.";
	exit 1;
fi
