#!/bin/bash

# vmreset
# virtualbox, reset machine power state
# by robert klebe, dotpointer

# changelog
# 2014-10-01 11:21:18
# 2018-06-29 17:04:00 - cleanup

# if machine is specified, stop that
if [ -n "$1" ]; then
    vboxmanage controlvm "$1" reset
    # otherwise stop them all
else
    echo "VM name must be specified";
fi
