#!/bin/bash

# vmrealcd
# virtualbox, mount sata optical drive
# by robert klebe, dotpointer

# changelog
# 2014-06-17 11:30:28
# 2018-06-29 17:01:00 - cleanup

VBoxManage storageattach "$1" --storagectl "SATA Controller" --port 1 --device 0 --type dvddrive --medium host:/dev/hdb --passthrough on
