#!/bin/bash

# vmstart
# virtualbox, start a machine
# by robert klebe, dotpointer

# changelog
# 2014-10-01 12:08:34
# 2018-06-29 17:07:00 - cleanup

# if machine is specified, start that
if [ -n "$1" ]; then
	nice -n 10 VBoxHeadless --startvm "$1" &
# otherwise end here
else
	echo 'Machine name must be specified';
	exit 1;
fi
