#!/bin/bash
# to stop virtual machines

# if machine is specified, stop that
if [ -n "$1" ]; then
    VBoxManage controlvm "$1" poweroff
# otherwise stop them all
else
   echo 'VM name must be specified';
   exit 1;
fi

