#!/bin/bash

# vmstop
# virtualbox, stop a machine
# by robert klebe, dotpointer

# changelog
# 2014-10-01 12:09:18
# 2018-06-29 17:09:00 - cleanup
# 2018-07-19 19:29:35 - indentation change, tab to 2 spaces

# if machine is specified, stop that
if [ -n "$1" ]; then
   VBoxManage controlvm "$1" poweroff
# otherwise stop them all
else
  echo 'VM name must be specified';
  exit 1;
fi
